apiVersion: v1
kind: Namespace
metadata:
  name: omada
---
apiVersion: v1
kind: Service
metadata:
  name: omada
  namespace: omada
  labels:
    app: omada
spec:
  clusterIP: None
  selector:
    app: omada
  ports:
    - name: web-https
      port: 8043
      targetPort: 8043
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-data
  namespace: omada
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: omada
  namespace: omada
spec:
  serviceName: omada
  replicas: 1
  selector:
    matchLabels:
      app: omada
  template:
    metadata:
      labels:
        app: omada
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        fsGroup: 508
      containers:
        - name: controller
          image: mbentley/omada-controller:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Warsaw"
          ports:
            - name: web-https
              containerPort: 8043
              protocol: TCP
            - name: web-http
              containerPort: 8088
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /opt/tplink/EAPController/data
            - name: work
              mountPath: /opt/tplink/EAPController/work
            - name: logs
              mountPath: /opt/tplink/EAPController/logs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: omada-data
        - name: work
          emptyDir: {}
        - name: logs
          emptyDir: {}