apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - containerPort: 8123
          env:
            - name: TZ
              value: "Europe/Moscow"  # (опционально) твой часовой пояс
            - name: HOMEASSISTANT_TRUSTED_PROXIES
              value: "0.0.0.0/0"
            - name: HOMEASSISTANT_INTERNAL_URL
              value: "http://192.168.0.101"
            - name: HOMEASSISTANT_EXTERNAL_URL
              value: "http://192.168.0.101"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-pvc