apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: torrserver
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-torrserver-prefix@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /torrserver
            pathType: Prefix
            backend:
              service:
                name: torrserver
                port:
                  number: 80